### PR TITLE
fix: just some wording changes, and some formatting consistency (blan…

### PR DESCRIPTION
**Pull request by fuzzy**
…k lines)

### CODE REVIEW

**Comment by fuzzy** [comment]
sorry, didn't catch the ... broken commit message until after I hit the button

**Comment by fermarsan** [comment]
Thank you for all your contributions, especially correcting errors in English (my native language is Spanish)

**Comment by fuzzy** [comment]
Happy to help. I hope to be contributing more substantial PR's soon. I've got a couple projects to get out of the way but then I hope to start helping with the AVR support, and have been toying with the idea of a Stdlib sort of thing that has "drivers" for common chips, with the aim of being used in further user abstractions.

**Comment by fermarsan** [comment]
Great, all your help will be well received.

**Comment by fermarsan** [comment]
Sorry, I made a mistake re-basing the **develop** branch when I was merging your contributions, so you doesn't appear as contributor despite your changes were applied. This is not very relevant, but I don't want you to think that your contributions have not been taken into account. If you consider it important, you can do any minimal contribution and PR in order to appear as contributor.

**Pull request merged**
